"""R_rank covert-channel capacity (rank entropy) vs MODEL SCALE across families.

For each model we reproduce the CORRECTED codebook capacity orientation
(reference = codebook M_int post-Gumbel scores, served = FP8 post-Gumbel argmax,
shared Gumbel seed), but on ON-POLICY tokens generated by the model itself
(bf16, T=1.0, top_p=1.0). We score ONLY completion positions, compute the
post-Gumbel rank of the served token at each completion position, and report

    R_rank = Shannon entropy (bits) of the empirical rank distribution
           = -sum_r p_r log2 p_r

over all kept completion tokens, where p_r = fraction of completion tokens whose
served-token rank == r. Vocab-agnostic (read from logits.shape[-1]).

Pipeline (per model, ONE at a time, bf16):
  1. generate on-policy completions from ~48 dolly instructions (>=~5000 comp tokens)
  2. FP8 teacher (served) teacher-forced forward over full sequences
  3. codebook M_int (reference) teacher-forced forward over full sequences
  4. post-Gumbel rank at each pos; keep completion-position ranks only
  5. R_rank = entropy of rank distribution

Run:
  IMA_TEACHER_KERNEL=fp8_scaled_mm /root/int-model-env/bin/python \
      capacity/rank_entropy_sweep.py --nprompts 48
"""
import argparse
import gc
import json
import os
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MEASURE = os.path.join(ROOT, "measure")
BUFFER = os.path.join(ROOT, "buffer")
PARETO = "/workspace/projects/int-model-approximation/results/llama_pareto"
for p in (MEASURE, BUFFER, PARETO):
    sys.path.insert(0, p)

from difr_baseline import GpuLock, DOLLY  # noqa: E402

ROWSEED = 20260616
GSEED_BASE = 40000000
MAX_NEW = 128
TARGET_COMP_TOKENS = 5000   # target per the task
MIN_COMP_TOKENS = 3000      # hard floor: below this generation basically failed
GEN_SEED = 1234

# (label, model_id, family, fp8_native)
MODELS = [
    # Qwen2.5 bf16
    ("qwen2.5-0.5b", "Qwen/Qwen2.5-0.5B", "qwen2.5", False),
    ("qwen2.5-1.5b", "Qwen/Qwen2.5-1.5B", "qwen2.5", False),
    ("qwen2.5-3b",   "Qwen/Qwen2.5-3B",   "qwen2.5", False),
    # Qwen2.5 FP8-native
    ("qwen2.5-0.5b-fp8", "RedHatAI/Qwen2.5-0.5B-Instruct-FP8-dynamic", "qwen2.5", True),
    ("qwen2.5-1.5b-fp8", "RedHatAI/Qwen2.5-1.5B-Instruct-FP8-dynamic", "qwen2.5", True),
    ("qwen2.5-3b-fp8",   "RedHatAI/Qwen2.5-3B-Instruct-FP8-dynamic",   "qwen2.5", True),
    # Llama bf16 (gated -> fallbacks)
    ("llama-3.2-1b", "meta-llama/Llama-3.2-1B", "llama", False),
    ("llama-3.2-3b", "meta-llama/Llama-3.2-3B", "llama", False),
    ("llama-68m",    "JackFram/llama-68m",      "llama-open", False),
    ("llama-160m",   "JackFram/llama-160m",     "llama-open", False),
    ("tinyllama-1.1b", "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T", "llama-open", False),
    # Llama FP8-native (8B - try, skip if OOM)
    ("llama-3.1-8b-fp8", "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8", "llama", True),
    # Gemma bf16 (gated)
    ("gemma-2-2b",   "google/gemma-2-2b",   "gemma", False),
    ("gemma-3-1b",   "google/gemma-3-1b-pt", "gemma", False),
    ("gemma-3-4b",   "google/gemma-3-4b-pt", "gemma", False),
    # Others (open, breadth)
    ("smollm2-360m", "HuggingFaceTB/SmolLM2-360M",  "smollm2", False),
    ("smollm2-1.7b", "HuggingFaceTB/SmolLM2-1.7B",  "smollm2", False),
    ("phi-3-mini",   "microsoft/Phi-3-mini-4k-instruct", "phi3", False),
    ("olmo-1b",      "allenai/OLMo-1B-hf",          "olmo", False),
]


def load_prompts(n, seed):
    lines = open(DOLLY).read().splitlines()
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(lines))
    out, seen = [], set()
    for i in idx:
        rec = json.loads(lines[i])
        t = (rec.get("instruction") or rec.get("context") or "").strip()
        if len(t) > 16 and t not in seen:
            seen.add(t)
            out.append(t)
        if len(out) == n:
            break
    return out


GEN_BATCH = 16


def generate_onpolicy(model, tok, prompts, max_seq=1024):
    """Batched on-policy generation. Returns list of (full_ids[1,L], comp_mask[L]).

    Left-pads prompts so we can batch model.generate; afterwards we strip the
    left padding and any trailing pad tokens, so each returned sequence is the
    real prompt_ids + completion_ids with a completion-only boolean mask.
    """
    import torch
    pad_id = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id
    eos_id = tok.eos_token_id
    old_side = tok.padding_side
    tok.padding_side = "left"
    seqs = []
    total_comp = 0
    torch.manual_seed(GEN_SEED)
    for i in range(0, len(prompts), GEN_BATCH):
        batch = prompts[i:i + GEN_BATCH]
        enc = tok(batch, return_tensors="pt", add_special_tokens=True,
                  padding=True, truncation=True, max_length=max_seq - MAX_NEW)
        input_ids = enc.input_ids.to("cuda")
        attn = enc.attention_mask.to("cuda")
        plen = input_ids.shape[1]  # padded prompt length (left padding)
        with torch.no_grad():
            out = model.generate(
                input_ids,
                attention_mask=attn,
                do_sample=True,
                temperature=1.0,
                top_p=1.0,
                max_new_tokens=MAX_NEW,
                pad_token_id=pad_id,
            )
        out = out.cpu()
        attn_cpu = attn.cpu()
        for b in range(out.shape[0]):
            row = out[b]
            n_real_prompt = int(attn_cpu[b].sum().item())
            # real prompt tokens are the rightmost n_real_prompt of the prompt block
            prompt_ids = row[plen - n_real_prompt: plen]
            comp_ids = row[plen:]
            # trim at first EOS in completion (inclusive of nothing past it)
            if eos_id is not None:
                eos_pos = (comp_ids == eos_id).nonzero()
                if eos_pos.numel() > 0:
                    comp_ids = comp_ids[: int(eos_pos[0].item()) + 1]
            # also strip any trailing pad ids
            if comp_ids.numel() > 0 and pad_id is not None:
                keep = comp_ids != pad_id
                # keep contiguous head until first pad
                if (~keep).any():
                    first_pad = int((~keep).nonzero()[0].item())
                    comp_ids = comp_ids[:first_pad]
            if comp_ids.numel() == 0:
                continue
            full = torch.cat([prompt_ids, comp_ids]).unsqueeze(0)
            if full.shape[1] > max_seq:
                full = full[:, :max_seq]
            L = full.shape[1]
            pl = prompt_ids.numel()
            comp = L - pl
            if comp <= 0:
                continue
            mask = np.zeros(L, dtype=bool)
            mask[pl:] = True
            seqs.append((full, mask))
            total_comp += comp
    tok.padding_side = old_side
    return seqs, total_comp


def ranks_for_seqs(z_fp8, z_int, masks):
    """Post-Gumbel rank of served token at every position; keep completion mask only.

    z_fp8[i], z_int[i]: numpy [L, V] float32. masks[i]: bool [L].
    Returns 1D int array of ranks over kept completion positions.
    """
    import torch
    kept = []
    for pi in range(len(z_fp8)):
        zf = torch.from_numpy(z_fp8[pi]).to("cuda").float()
        zr = torch.from_numpy(z_int[pi]).to("cuda").float()  # reference = codebook
        g = torch.empty(zf.shape, device="cuda", dtype=torch.float32)
        gen = torch.Generator(device="cuda")
        gen.manual_seed(GSEED_BASE + 1 + pi)
        g.exponential_(generator=gen).log_().neg_()
        zrf = zr + g
        zsf = zf + g
        ref_pref = zrf.max(dim=-1).values
        srv_tok = zsf.argmax(dim=-1)
        delta = ref_pref[:, None] - zrf
        margin = delta.gather(-1, srv_tok[:, None]).squeeze(-1)
        ds, _ = torch.sort(delta, dim=-1)
        rank = torch.searchsorted(ds, margin[:, None], right=False).squeeze(-1)
        rank = rank.cpu().numpy().astype(np.int64)
        m = masks[pi]
        kept.append(rank[m])
        del zf, zr, g, zrf, zsf, delta, ds, rank
        torch.cuda.empty_cache()
    return np.concatenate(kept)


def rank_entropy_bits(ranks):
    """Shannon entropy (bits) of the empirical rank distribution."""
    vals, counts = np.unique(ranks, return_counts=True)
    p = counts.astype(np.float64) / counts.sum()
    return float(-(p * np.log2(p)).sum())


def model_run(model_id, prompts, fp8_native):
    """Return dict of results for one model."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from int_model_approximation.__main__ import FP8Linear, CodebookLinear
    from llama_difr import replace_linears, forced_logits

    tok = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    if tok.pad_token_id is None:
        tok.pad_token = tok.eos_token  # needed for batched left-padded generation

    def fresh():
        m = AutoModelForCausalLM.from_pretrained(
            model_id, torch_dtype=torch.bfloat16, trust_remote_code=True
        )
        return m.to("cuda").eval()

    with GpuLock():
        # ---- on-policy generation with bf16 model (the policy) ----
        gen_model = fresh()
        n_params = sum(p.numel() for p in gen_model.parameters())
        seqs, total_comp = generate_onpolicy(gen_model, tok, prompts)
        # if not enough completion tokens, keep generating with extra prompts
        del gen_model
        gc.collect()
        torch.cuda.empty_cache()

        if total_comp < MIN_COMP_TOKENS:
            raise RuntimeError(
                f"only {total_comp} completion tokens (< {MIN_COMP_TOKENS})"
            )
        if total_comp < TARGET_COMP_TOKENS:
            print(f"  WARN only {total_comp} completion tokens "
                  f"(< target {TARGET_COMP_TOKENS}); proceeding", flush=True)

        ids_list = [full.to("cuda") for full, _ in seqs]
        masks = [m for _, m in seqs]

        # ---- FP8 teacher (served) ----
        teacher = fresh()
        n_swapped = replace_linears(teacher, lambda w, s, b: FP8Linear(w, s, b))
        if n_swapped == 0:
            del teacher
            torch.cuda.empty_cache()
            raise RuntimeError("replace_linears swapped 0 linears (unsupported arch)")
        z_fp8 = []
        with torch.no_grad():
            for ids in ids_list:
                z_fp8.append(forced_logits(teacher, ids).cpu().numpy().astype(np.float32))
        del teacher
        gc.collect()
        torch.cuda.empty_cache()

        # ---- codebook M_int (reference) ----
        student = fresh()
        replace_linears(student, lambda w, s, b: CodebookLinear(w, s, b))
        z_int = []
        with torch.no_grad():
            for ids in ids_list:
                z_int.append(forced_logits(student, ids).cpu().numpy().astype(np.float32))
        del student
        gc.collect()
        torch.cuda.empty_cache()

        vocab = int(z_fp8[0].shape[-1])
        ranks = ranks_for_seqs(z_fp8, z_int, masks)

    R_rank = rank_entropy_bits(ranks)
    frac_rank0 = float((ranks == 0).mean())
    return {
        "n_params": int(n_params),
        "vocab": vocab,
        "n_completion_tokens": int(ranks.size),
        "n_swapped": int(n_swapped),
        "R_rank": R_rank,
        "frac_rank0": frac_rank0,
        "max_rank": int(ranks.max()),
        "mean_rank": float(ranks.mean()),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--nprompts", type=int, default=64)
    ap.add_argument("--only", type=str, default=None,
                    help="comma-sep labels to run (validation)")
    a = ap.parse_args()
    assert os.environ.get("IMA_TEACHER_KERNEL") == "fp8_scaled_mm", \
        "run with IMA_TEACHER_KERNEL=fp8_scaled_mm"

    prompts = load_prompts(a.nprompts, ROWSEED)
    print(f"{len(prompts)} seed prompts", flush=True)

    models = MODELS
    if a.only:
        want = set(a.only.split(","))
        models = [m for m in MODELS if m[0] in want]

    outp = os.path.join(HERE, "rank_entropy_results.json")
    results = []
    if os.path.exists(outp) and not a.only:
        try:
            results = json.load(open(outp))
        except Exception:
            results = []
    done = {r["label"] for r in results if "R_rank" in r}

    for label, mid, family, fp8 in models:
        if label in done:
            print(f"SKIP (done) {label}", flush=True)
            continue
        t0 = time.time()
        print(f"=== {label} ({mid}) family={family} fp8_native={fp8} ===", flush=True)
        try:
            r = model_run(mid, prompts, fp8)
            rec = {"label": label, "model_id": mid, "family": family,
                   "fp8_native": fp8, **r, "secs": round(time.time() - t0, 1)}
        except Exception as e:
            import traceback
            traceback.print_exc()
            rec = {"label": label, "model_id": mid, "family": family,
                   "fp8_native": fp8, "ERROR": str(e)[:400],
                   "secs": round(time.time() - t0, 1)}
        # replace any prior entry for this label
        results = [x for x in results if x["label"] != label]
        results.append(rec)
        json.dump(results, open(outp, "w"), indent=2)
        print("RESULT " + json.dumps(rec), flush=True)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
