"""R_rank covert-channel capacity (rank entropy) vs MODEL SCALE across families.

For each model we reproduce the CORRECTED codebook capacity orientation
(reference = codebook M_int post-Gumbel scores, served = FP8 post-Gumbel argmax,
shared Gumbel seed), but on ON-POLICY tokens generated by the model itself
(T=1.0, top_p=1.0). We score ONLY completion positions, compute the
post-Gumbel rank of the served token at each completion position, and report

    R_rank = Shannon entropy (bits) of the empirical rank distribution
           = -sum_r p_r log2 p_r

over all kept completion tokens, where p_r = fraction of completion tokens whose
served-token rank == r. Vocab-agnostic (read from logits.shape[-1]).

KEY FIX (vs prior run): INSTRUCT / chat models are now generated WITH their chat
template (apply_chat_template, add_generation_prompt=True). BASE models keep plain
prompt continuation. The prior run fed bare instructions to FP8 *instruct*
checkpoints -> off-distribution degenerate generation -> extreme activations ->
the codebook per-token FP8 int path loses precision on outlier rows -> huge logit
errors -> inflated R_rank/mean_rank. We test whether the template fix resolves it.

DIAGNOSTICS recorded per model (to decide artifact vs real):
  - mean_rank, max_rank (served-token post-Gumbel rank stats)
  - sat_rate      : fraction of completion positions where the max |z_fp8 - z_cb|
                    logit divergence exceeds SAT_LOGIT_THRESH (proxy for the
                    activation-outlier saturation that wrecks the codebook int path)
  - act_absmax_p99/max : 99th-pct / max per-token activation absmax seen by the
                    swapped linears during the codebook forward (hooks). Large
                    values => outlier rows => big per-token-FP8 quantization error.

Pipeline (per model, ONE at a time, bf16):
  1. generate on-policy completions (chat template if instruct), >=~5000 comp tokens
  2. FP8 teacher (served) teacher-forced forward over full sequences
  3. codebook M_int (reference) teacher-forced forward, WITH activation hooks
  4. post-Gumbel rank at each pos; keep completion-position ranks only
  5. R_rank = entropy of rank distribution; diagnostics as above

Run:
  IMA_TEACHER_KERNEL=fp8_scaled_mm /root/int-model-env/bin/python \
      capacity/rank_entropy_sweep.py --nprompts 64
Validate one model first:
  ... capacity/rank_entropy_sweep.py --only qwen2.5-0.5b-fp8
"""
import argparse
import gc
import json
import os
import sys
import time

import numpy as np

# ---- make sure HF token is exported (gated repos) ----
if not os.environ.get("HF_TOKEN"):
    envp = "/workspace/.env"
    if os.path.exists(envp):
        for line in open(envp):
            line = line.strip()
            if line.startswith("HF_TOKEN=") and "=" in line:
                os.environ["HF_TOKEN"] = line.split("=", 1)[1].strip()
                break
if os.environ.get("HF_TOKEN"):
    os.environ.setdefault("HUGGING_FACE_HUB_TOKEN", os.environ["HF_TOKEN"])

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
MEASURE = os.path.join(ROOT, "measure")
BUFFER = os.path.join(ROOT, "buffer")
PARETO = "/workspace/projects/int-model-approximation/results/llama_pareto"
for p in (MEASURE, BUFFER, PARETO):
    sys.path.insert(0, p)

from difr_baseline import GpuLock, DOLLY  # noqa: E402

ROWSEED = 20260616
GSEED_BASE = 40000000
MAX_NEW = 128
TARGET_COMP_TOKENS = 5000   # target per the task
MIN_COMP_TOKENS = 3000      # hard floor: below this generation basically failed
GEN_SEED = 1234
SAT_LOGIT_THRESH = 5.0      # |z_fp8 - z_cb|_max above this => "saturated"/diverged pos

HF_TOKEN = os.environ.get("HF_TOKEN")

# (label, model_id, family, fp8_native, instruct)
MODELS = [
    # ---- Qwen2.5 base (bf16) ----
    ("qwen2.5-0.5b", "Qwen/Qwen2.5-0.5B", "qwen2.5", False, False),
    ("qwen2.5-1.5b", "Qwen/Qwen2.5-1.5B", "qwen2.5", False, False),
    ("qwen2.5-3b",   "Qwen/Qwen2.5-3B",   "qwen2.5", False, False),
    # ---- Qwen2.5 instruct (bf16) -- matched bf16 partner for the FP8-native instruct ----
    ("qwen2.5-0.5b-inst", "Qwen/Qwen2.5-0.5B-Instruct", "qwen2.5", False, True),
    ("qwen2.5-1.5b-inst", "Qwen/Qwen2.5-1.5B-Instruct", "qwen2.5", False, True),
    ("qwen2.5-3b-inst",   "Qwen/Qwen2.5-3B-Instruct",   "qwen2.5", False, True),
    # ---- Qwen2.5 FP8-native (instruct) ----
    ("qwen2.5-0.5b-fp8", "RedHatAI/Qwen2.5-0.5B-Instruct-FP8-dynamic", "qwen2.5", True, True),
    ("qwen2.5-1.5b-fp8", "RedHatAI/Qwen2.5-1.5B-Instruct-FP8-dynamic", "qwen2.5", True, True),
    ("qwen2.5-3b-fp8",   "RedHatAI/Qwen2.5-3B-Instruct-FP8-dynamic",   "qwen2.5", True, True),
    # ---- Llama-3.2 base (bf16, gated) ----
    ("llama-3.2-1b", "meta-llama/Llama-3.2-1B", "llama", False, False),
    ("llama-3.2-3b", "meta-llama/Llama-3.2-3B", "llama", False, False),
    # ---- Llama FP8-native (8B instruct, static FP8) -- try, may OOM/skip ----
    ("llama-3.1-8b-fp8", "RedHatAI/Meta-Llama-3.1-8B-Instruct-FP8", "llama", True, True),
    # ---- llama-open (open small base) ----
    ("llama-68m",    "JackFram/llama-68m",  "llama-open", False, False),
    ("llama-160m",   "JackFram/llama-160m", "llama-open", False, False),
    ("tinyllama-1.1b", "TinyLlama/TinyLlama-1.1B-intermediate-step-1431k-3T", "llama-open", False, False),
    # ---- Gemma base (gated) ----
    ("gemma-3-1b",   "google/gemma-3-1b-pt", "gemma", False, False),
    ("gemma-3-4b",   "google/gemma-3-4b-pt", "gemma", False, False),
    ("gemma-2-2b",   "google/gemma-2-2b",    "gemma", False, False),
    # ---- SmolLM2 base ----
    ("smollm2-360m", "HuggingFaceTB/SmolLM2-360M", "smollm2", False, False),
    ("smollm2-1.7b", "HuggingFaceTB/SmolLM2-1.7B", "smollm2", False, False),
    # ---- OLMo base ----
    ("olmo-1b",      "allenai/OLMo-1B-hf",   "olmo", False, False),
]


def load_prompts(n, seed):
    lines = open(DOLLY).read().splitlines()
    rng = np.random.default_rng(seed)
    idx = rng.permutation(len(lines))
    out, seen = [], set()
    for i in idx:
        rec = json.loads(lines[i])
        t = (rec.get("instruction") or rec.get("context") or "").strip()
        if len(t) > 16 and t not in seen:
            seen.add(t)
            out.append(t)
        if len(out) == n:
            break
    return out


GEN_BATCH = 16


def _build_inputs(tok, batch, instruct, max_len):
    """Tokenize a batch of prompts. Instruct -> chat template; base -> plain."""
    import torch
    if instruct and tok.chat_template is not None:
        texts = [
            tok.apply_chat_template(
                [{"role": "user", "content": p}],
                add_generation_prompt=True, tokenize=False,
            )
            for p in batch
        ]
        enc = tok(texts, return_tensors="pt", add_special_tokens=False,
                  padding=True, truncation=True, max_length=max_len)
    else:
        enc = tok(batch, return_tensors="pt", add_special_tokens=True,
                  padding=True, truncation=True, max_length=max_len)
    return enc


def generate_onpolicy(model, tok, prompts, instruct, max_seq=1024):
    """Batched on-policy generation. Returns list of (full_ids[1,L], comp_mask[L]).

    Left-pads prompts so we can batch model.generate; afterwards we strip the
    left padding and any trailing pad tokens, so each returned sequence is the
    real prompt_ids + completion_ids with a completion-only boolean mask.
    For instruct models the "prompt" is the rendered chat template.
    """
    import torch
    pad_id = tok.pad_token_id if tok.pad_token_id is not None else tok.eos_token_id
    eos_id = tok.eos_token_id
    old_side = tok.padding_side
    tok.padding_side = "left"
    seqs = []
    total_comp = 0
    torch.manual_seed(GEN_SEED)
    for i in range(0, len(prompts), GEN_BATCH):
        batch = prompts[i:i + GEN_BATCH]
        enc = _build_inputs(tok, batch, instruct, max_seq - MAX_NEW)
        input_ids = enc.input_ids.to("cuda")
        attn = enc.attention_mask.to("cuda")
        plen = input_ids.shape[1]  # padded prompt length (left padding)
        with torch.no_grad():
            out = model.generate(
                input_ids,
                attention_mask=attn,
                do_sample=True,
                temperature=1.0,
                top_p=1.0,
                max_new_tokens=MAX_NEW,
                pad_token_id=pad_id,
            )
        out = out.cpu()
        attn_cpu = attn.cpu()
        for b in range(out.shape[0]):
            row = out[b]
            n_real_prompt = int(attn_cpu[b].sum().item())
            prompt_ids = row[plen - n_real_prompt: plen]
            comp_ids = row[plen:]
            if eos_id is not None:
                eos_pos = (comp_ids == eos_id).nonzero()
                if eos_pos.numel() > 0:
                    comp_ids = comp_ids[: int(eos_pos[0].item()) + 1]
            if comp_ids.numel() > 0 and pad_id is not None:
                keep = comp_ids != pad_id
                if (~keep).any():
                    first_pad = int((~keep).nonzero()[0].item())
                    comp_ids = comp_ids[:first_pad]
            if comp_ids.numel() == 0:
                continue
            full = torch.cat([prompt_ids, comp_ids]).unsqueeze(0)
            if full.shape[1] > max_seq:
                full = full[:, :max_seq]
            L = full.shape[1]
            pl = prompt_ids.numel()
            comp = L - pl
            if comp <= 0:
                continue
            mask = np.zeros(L, dtype=bool)
            mask[pl:] = True
            seqs.append((full, mask))
            total_comp += comp
    tok.padding_side = old_side
    return seqs, total_comp


def ranks_for_seqs(z_fp8, z_int, masks):
    """Post-Gumbel rank of served token at every position; keep completion mask only.

    z_fp8[i], z_int[i]: numpy [L, V] float32. masks[i]: bool [L].
    Returns 1D int array of ranks over kept completion positions.
    """
    import torch
    kept = []
    for pi in range(len(z_fp8)):
        zf = torch.from_numpy(z_fp8[pi]).to("cuda").float()
        zr = torch.from_numpy(z_int[pi]).to("cuda").float()  # reference = codebook
        g = torch.empty(zf.shape, device="cuda", dtype=torch.float32)
        gen = torch.Generator(device="cuda")
        gen.manual_seed(GSEED_BASE + 1 + pi)
        g.exponential_(generator=gen).log_().neg_()
        zrf = zr + g
        zsf = zf + g
        srv_tok = zsf.argmax(dim=-1)                          # lowest-id tie-break (consistent)
        s = zrf.gather(-1, srv_tok[:, None])                 # served token's reference score
        ids = torch.arange(zrf.shape[-1], device=zrf.device)[None, :]
        gt = (zrf > s).sum(dim=-1)                           # strictly greater score => above
        eq_lower = ((zrf == s) & (ids < srv_tok[:, None])).sum(dim=-1)  # tie & lower id => above
        rank = (gt + eq_lower).cpu().numpy().astype(np.int64)  # ties broken by token ID
        m = masks[pi]
        kept.append(rank[m])
        del zf, zr, g, zrf, zsf, s, ids, gt, eq_lower, rank
        torch.cuda.empty_cache()
    return np.concatenate(kept)


def logit_divergence_sat(z_fp8, z_int, masks):
    """Per completion position: max_v |z_fp8 - z_cb|. Returns sat_rate and stats.

    Proxy for the activation-outlier / int-path saturation that corrupts the
    codebook reference. A position counts as "saturated/diverged" when the worst
    per-vocab logit gap exceeds SAT_LOGIT_THRESH.
    """
    maxgaps = []
    for pi in range(len(z_fp8)):
        d = np.abs(z_fp8[pi] - z_int[pi]).max(axis=-1)  # [L]
        maxgaps.append(d[masks[pi]])
    g = np.concatenate(maxgaps)
    return {
        "sat_rate": float((g > SAT_LOGIT_THRESH).mean()),
        "logit_gap_mean": float(g.mean()),
        "logit_gap_p99": float(np.quantile(g, 0.99)),
        "logit_gap_max": float(g.max()),
    }


def rank_entropy_bits(ranks):
    """Shannon entropy (bits) of the empirical rank distribution."""
    vals, counts = np.unique(ranks, return_counts=True)
    p = counts.astype(np.float64) / counts.sum()
    return float(-(p * np.log2(p)).sum())


def _iter_decoder_layers(model):
    """Return the list of transformer decoder layers, robust to arch nesting
    (Gemma3ForConditionalGeneration nests the text model under .language_model)."""
    import torch.nn as nn
    # common: model.model.layers
    candidates = []
    base = getattr(model, "model", model)
    for attr_chain in (("layers",), ("language_model", "layers"),
                       ("text_model", "layers"), ("decoder", "layers")):
        obj = base
        ok = True
        for a in attr_chain:
            if hasattr(obj, a):
                obj = getattr(obj, a)
            else:
                ok = False
                break
        if ok and isinstance(obj, nn.ModuleList):
            return obj
    # last resort: find the largest ModuleList of decoder-ish layers
    best = None
    for m in model.modules():
        if isinstance(m, nn.ModuleList) and len(m) > 0 and hasattr(m[0], "self_attn"):
            if best is None or len(m) > len(best):
                best = m
    if best is None:
        raise RuntimeError("could not locate decoder layers")
    return best


TARGETS = ("q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj")


def _true_weight(mod):
    """Return the real (dequantized) weight of a linear, in float32.

    Compressed-tensors FP8-native checkpoints decompress to a plain nn.Linear
    whose .weight is STILL raw float8_e4m3fn codes (absmax 448) with a SEPARATE
    .weight_scale parameter that is NOT folded in. If we read .weight naively we
    get ~350x-too-large weights -> exploding activations -> bogus R_rank. Fold the
    per-row weight_scale here so we always re-quantize the served weights.
    """
    import torch
    w = mod.weight
    ws = getattr(mod, "weight_scale", None)
    if w.dtype == torch.float8_e4m3fn or ws is not None:
        wf = w.detach().float()
        if ws is not None:
            wf = wf * ws.detach().float().reshape(-1, 1)
        return wf
    return w.detach().float()


def replace_linears_robust(model, factory):
    """Swap targeted nn.Linear -> factory(w_fp8, w_scale, bias) across arch variants.
    Returns (n_swapped, list_of_swapped_modules)."""
    import torch.nn as nn
    from llama_difr import quantize_fp8_per_row
    layers = _iter_decoder_layers(model)
    n = 0
    swapped = []
    for layer in layers:
        parents = []
        if hasattr(layer, "self_attn"):
            parents.append(layer.self_attn)
        if hasattr(layer, "mlp"):
            parents.append(layer.mlp)
        for parent in parents:
            for name, mod in list(parent.named_children()):
                if isinstance(mod, nn.Linear) and name in TARGETS:
                    w_fp8, w_scale = quantize_fp8_per_row(_true_weight(mod))
                    new = factory(w_fp8, w_scale, mod.bias).to("cuda")
                    setattr(parent, name, new)
                    swapped.append(new)
                    n += 1
    return n, swapped


def model_run(label, model_id, family, fp8_native, instruct, prompts):
    """Return dict of results for one model."""
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from int_model_approximation.__main__ import FP8Linear, CodebookLinear
    from llama_difr import forced_logits

    tok = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True, token=HF_TOKEN)
    if tok.pad_token_id is None:
        tok.pad_token = tok.eos_token

    def fresh():
        m = AutoModelForCausalLM.from_pretrained(
            model_id, torch_dtype=torch.bfloat16, trust_remote_code=True,
            token=HF_TOKEN,
        )
        return m.to("cuda").eval()

    with GpuLock():
        # ---- on-policy generation with bf16 model (the policy) ----
        gen_model = fresh()
        n_params = sum(p.numel() for p in gen_model.parameters())
        seqs, total_comp = generate_onpolicy(gen_model, tok, prompts, instruct)
        del gen_model
        gc.collect()
        torch.cuda.empty_cache()

        if total_comp < MIN_COMP_TOKENS:
            raise RuntimeError(
                f"only {total_comp} completion tokens (< {MIN_COMP_TOKENS})"
            )
        if total_comp < TARGET_COMP_TOKENS:
            print(f"  WARN only {total_comp} completion tokens "
                  f"(< target {TARGET_COMP_TOKENS}); proceeding", flush=True)

        ids_list = [full.to("cuda") for full, _ in seqs]
        masks = [m for _, m in seqs]

        # ---- FP8 teacher (served) ----
        teacher = fresh()
        n_swapped, _ = replace_linears_robust(teacher, lambda w, s, b: FP8Linear(w, s, b))
        if n_swapped == 0:
            del teacher
            torch.cuda.empty_cache()
            raise RuntimeError("replace_linears swapped 0 linears (unsupported arch)")
        z_fp8 = []
        with torch.no_grad():
            for ids in ids_list:
                z_fp8.append(forced_logits(teacher, ids).cpu().numpy().astype(np.float32))
        del teacher
        gc.collect()
        torch.cuda.empty_cache()

        # ---- codebook M_int (reference) WITH activation hooks ----
        student = fresh()
        _, sw = replace_linears_robust(student, lambda w, s, b: CodebookLinear(w, s, b))
        act_absmax_running = []  # collect per-token absmax over all swapped linears

        def mk_hook():
            def hook(mod, inp, out):
                x = inp[0]
                # per-token (row) absmax of the linear input
                a = x.reshape(-1, x.shape[-1]).abs().amax(dim=-1)
                act_absmax_running.append(float(a.max().item()))
            return hook

        handles = [m.register_forward_hook(mk_hook()) for m in sw]
        z_int = []
        with torch.no_grad():
            for ids in ids_list:
                z_int.append(forced_logits(student, ids).cpu().numpy().astype(np.float32))
        for h in handles:
            h.remove()
        del student
        gc.collect()
        torch.cuda.empty_cache()

        vocab = int(z_fp8[0].shape[-1])
        ranks = ranks_for_seqs(z_fp8, z_int, masks)
        satinfo = logit_divergence_sat(z_fp8, z_int, masks)

    R_rank = rank_entropy_bits(ranks)
    frac_rank0 = float((ranks == 0).mean())
    act = np.array(act_absmax_running, dtype=np.float64) if act_absmax_running else np.array([0.0])
    return {
        "n_params": int(n_params),
        "vocab": vocab,
        "n_completion_tokens": int(ranks.size),
        "n_swapped": int(n_swapped),
        "R_rank": R_rank,
        "frac_rank0": frac_rank0,
        "max_rank": int(ranks.max()),
        "mean_rank": float(ranks.mean()),
        "act_absmax_p99": float(np.quantile(act, 0.99)),
        "act_absmax_max": float(act.max()),
        **satinfo,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--nprompts", type=int, default=64)
    ap.add_argument("--only", type=str, default=None,
                    help="comma-sep labels to run (validation)")
    ap.add_argument("--force", action="store_true",
                    help="re-run even if label already has a result")
    a = ap.parse_args()
    assert os.environ.get("IMA_TEACHER_KERNEL") == "fp8_scaled_mm", \
        "run with IMA_TEACHER_KERNEL=fp8_scaled_mm"

    prompts = load_prompts(a.nprompts, ROWSEED)
    print(f"{len(prompts)} seed prompts; HF_TOKEN set={bool(HF_TOKEN)}", flush=True)

    models = MODELS
    if a.only:
        want = set(a.only.split(","))
        models = [m for m in MODELS if m[0] in want]

    outp = os.path.join(HERE, "rank_entropy_results.json")
    results = []
    if os.path.exists(outp):
        try:
            results = json.load(open(outp))
        except Exception:
            results = []
    done = {r["label"] for r in results if "R_rank" in r}

    for label, mid, family, fp8, instruct in models:
        if label in done and not a.force and not a.only:
            print(f"SKIP (done) {label}", flush=True)
            continue
        t0 = time.time()
        print(f"=== {label} ({mid}) family={family} fp8={fp8} instruct={instruct} ===",
              flush=True)
        try:
            r = model_run(label, mid, family, fp8, instruct, prompts)
            rec = {"label": label, "model_id": mid, "family": family,
                   "fp8_native": fp8, "instruct": instruct, **r,
                   "secs": round(time.time() - t0, 1)}
        except Exception as e:
            import traceback
            traceback.print_exc()
            rec = {"label": label, "model_id": mid, "family": family,
                   "fp8_native": fp8, "instruct": instruct, "ERROR": str(e)[:400],
                   "secs": round(time.time() - t0, 1)}
        results = [x for x in results if x["label"] != label]
        results.append(rec)
        json.dump(results, open(outp, "w"), indent=2)
        print("RESULT " + json.dumps(rec), flush=True)
    print("DONE", flush=True)


if __name__ == "__main__":
    main()
